name: Make sure my code is nice
on:
  push:

jobs:
  quality_assurance:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2

      - name: Check format
        run: dart format --line-length 120 --set-exit-if-changed ./lib

      - name: Analyze code
        run: |
          flutter config --no-analytics
          flutter analyze